# Generated by Django 4.1.6 on 2023-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "author",
                    models.CharField(max_length=50),
                ),
                (
                    "active",
                    models.BooleanField(default=True),
                ),
            ],
        ),
    ]
